import AnalyticNumberTheory.Dirichlet.LFunctionGrowth
import AnalyticNumberTheory.Dirichlet.RightHalfPlaneBounds
import AnalyticNumberTheory.Dirichlet.LocalLogDerivative
import AnalyticNumberTheory.Dirichlet.LFunctionAnchor
import AnalyticNumberTheory.Dirichlet.FiniteRectangleLogDerivative
import AnalyticNumberTheory.Dirichlet.CompletedReflection
import AnalyticNumberTheory.Dirichlet.ExplicitFormulaResidue

/-!
# Finite-rectangle Dirichlet logarithmic-derivative trust audit

Focused kernel audit for the externally sourced neutral growth, local complex-analysis,
anchor, finite-rectangle logarithmic-derivative, completed-functional-equation reflection,
and local explicit-formula residue block. CI enforces the same exact axiom whitelist as the
repository-wide audit.
-/

#print axioms AnalyticNumberTheory.Dirichlet.norm_LFunction_le_growth
#print axioms AnalyticNumberTheory.Dirichlet.tsum_nat_rpow_neg_le
#print axioms AnalyticNumberTheory.Dirichlet.norm_dirichletLFunction_le
#print axioms AnalyticNumberTheory.Dirichlet.exists_holomorphicLog_on_ball
#print axioms AnalyticNumberTheory.Dirichlet.norm_deriv_le_small_disk
#print axioms AnalyticNumberTheory.Dirichlet.norm_logDeriv_le_small_disk
#print axioms AnalyticNumberTheory.Dirichlet.delta_quarter_le_norm_LFunction_anchor
#print axioms AnalyticNumberTheory.Dirichlet.anchor_disk_re_lower
#print axioms AnalyticNumberTheory.Dirichlet.norm_LFunction_le_on_anchor_disk
#print axioms AnalyticNumberTheory.Dirichlet.anchor_disk_subset_rectangle
#print axioms AnalyticNumberTheory.Dirichlet.norm_logDeriv_LFunction_le_of_zeroFree_openLowerRectangle
#print axioms AnalyticNumberTheory.Dirichlet.norm_logDeriv_LFunction_le_of_zeroFree_rectangle
#print axioms AnalyticNumberTheory.Dirichlet.symmetricCompletedLFunction_one_sub
#print axioms AnalyticNumberTheory.Dirichlet.logDeriv_symmetricCompletedLFunction_one_sub
#print axioms AnalyticNumberTheory.Dirichlet.logDeriv_symmetricCompletedLFunction_eq_three_factors_of_regular
#print axioms AnalyticNumberTheory.Dirichlet.logDeriv_LFunction_eq_reflected_of_regular
#print axioms AnalyticNumberTheory.Dirichlet.residue_explicitFormulaIntegrand
