import AnalyticNumberTheory.Dirichlet.GRH
import AnalyticNumberTheory.Dirichlet.LocalLogDerivative
import AnalyticNumberTheory.Dirichlet.CharacterPrefix
import AnalyticNumberTheory.Dirichlet.AbelWeightVariation
import AnalyticNumberTheory.Dirichlet.ConditionalValueSeries
import AnalyticNumberTheory.Dirichlet.LFunctionGrowth
import AnalyticNumberTheory.Dirichlet.RightHalfPlaneBounds
import AnalyticNumberTheory.Dirichlet.VonMangoldtLSeries
import AnalyticNumberTheory.Dirichlet.Orthogonality
import AnalyticNumberTheory.Dirichlet.Decomposition
import AnalyticNumberTheory.Dirichlet.Moments
import AnalyticNumberTheory.Dirichlet.MomentBounds
import AnalyticNumberTheory.Dirichlet.TwistedMoments
import AnalyticNumberTheory.Dirichlet.PrimeWindowWeights
import AnalyticNumberTheory.Dirichlet.VonMangoldtWindow
import AnalyticNumberTheory.Dirichlet.VonMangoldtPartialSums
import AnalyticNumberTheory.PrimeDistribution.DyadicPrimeWindow

/-!
# Reusable analytic core trust audit

This focused audit covers the public theorems added by the extracted downstream-neutral
Dirichlet GRH/character layers together with the reusable dyadic prime-window layer used by
downstream analytic applications. CI enforces the same exact axiom whitelist as the
repository-wide audit.
-/

#print axioms AnalyticNumberTheory.Dirichlet.GRH.at
#print axioms AnalyticNumberTheory.Dirichlet.grhAt_iff
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.LFunction_ne_zero_of_half_lt_re
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.zeroFreeRectangle
#print axioms AnalyticNumberTheory.Dirichlet.exists_holomorphicLog_on_ball
#print axioms AnalyticNumberTheory.Dirichlet.norm_deriv_le_small_disk
#print axioms AnalyticNumberTheory.Dirichlet.norm_logDeriv_le_small_disk
#print axioms AnalyticNumberTheory.Dirichlet.character_norm_le_one
#print axioms AnalyticNumberTheory.Dirichlet.sum_one_period_eq_zero
#print axioms AnalyticNumberTheory.Dirichlet.sum_aligned_period_eq_zero
#print axioms AnalyticNumberTheory.Dirichlet.sum_mul_period_eq_zero
#print axioms AnalyticNumberTheory.Dirichlet.norm_sum_range_character_le_modulus
#print axioms AnalyticNumberTheory.Dirichlet.abel_Ico
#print axioms AnalyticNumberTheory.Dirichlet.hasDerivAt_cpowWeight
#print axioms AnalyticNumberTheory.Dirichlet.norm_cpowWeightDeriv
#print axioms AnalyticNumberTheory.Dirichlet.norm_cpowWeight_succ_sub_le_integral
#print axioms AnalyticNumberTheory.Dirichlet.norm_cpowWeight_succ_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.sum_norm_cpowWeight_sub_le_sub
#print axioms AnalyticNumberTheory.Dirichlet.sum_norm_cpowWeight_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.summable_norm_cpowWeight_sub
#print axioms AnalyticNumberTheory.Dirichlet.tsum_norm_cpowWeight_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.hasDerivAt_logCpowWeight
#print axioms AnalyticNumberTheory.Dirichlet.norm_logCpowWeightDeriv_le
#print axioms AnalyticNumberTheory.Dirichlet.hasDerivAt_logVariationBudget
#print axioms AnalyticNumberTheory.Dirichlet.norm_logCpowWeight_succ_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.sum_norm_logCpowWeight_sub_le_sub
#print axioms AnalyticNumberTheory.Dirichlet.sum_norm_logCpowWeight_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.summable_norm_logCpowWeight_sub
#print axioms AnalyticNumberTheory.Dirichlet.tsum_norm_logCpowWeight_sub_le
#print axioms AnalyticNumberTheory.Dirichlet.character_nat_zero_of_ne_one
#print axioms AnalyticNumberTheory.Dirichlet.cpowWeight_nat_eq
#print axioms AnalyticNumberTheory.Dirichlet.norm_sum_Ico_cpowWeight_character_le
#print axioms AnalyticNumberTheory.Dirichlet.tendsto_norm_cpowWeight_nat_atTop
#print axioms AnalyticNumberTheory.Dirichlet.tendsto_cpowVariationBudget_nat_atTop
#print axioms AnalyticNumberTheory.Dirichlet.cauchySeq_sum_range_cpowWeight_character
#print axioms AnalyticNumberTheory.Dirichlet.exists_tendsto_sum_range_cpowWeight_character
#print axioms AnalyticNumberTheory.Dirichlet.tendsto_sum_range_orderedValueSeries
#print axioms AnalyticNumberTheory.Dirichlet.norm_orderedValueSeries_sub_sum_range_le
#print axioms AnalyticNumberTheory.Dirichlet.orderedValueSeries_proof_irrel
#print axioms AnalyticNumberTheory.Dirichlet.orderedValueFunction_eq
#print axioms AnalyticNumberTheory.Dirichlet.tendstoLocallyUniformlyOn_valuePartialSum
#print axioms AnalyticNumberTheory.Dirichlet.differentiableOn_orderedValueFunction
#print axioms AnalyticNumberTheory.Dirichlet.orderedValueSeries_eq_LFunction
#print axioms AnalyticNumberTheory.Dirichlet.orderedValueSeries_eq_LFunction_of_re_pos
#print axioms AnalyticNumberTheory.Dirichlet.norm_LFunction_le_growth
#print axioms AnalyticNumberTheory.Dirichlet.norm_dirichletLFunction_le
#print axioms AnalyticNumberTheory.Dirichlet.twistedVonMangoldtLSeries_eq_negLogDerivLFunction
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.analyticAt_negLogDerivLFunction
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.analyticOnNhd_negLogDerivLFunction_halfPlane
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.exists_norm_negLogDerivLFunction_bound_on_compact
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.exists_norm_negLogDerivLFunction_bound_on_verticalSegment
#print axioms AnalyticNumberTheory.Dirichlet.norm_negLogDerivLFunction_le_vonMangoldtLSeriesMajorant
#print axioms AnalyticNumberTheory.Dirichlet.norm_negLogDerivLFunction_le_vonMangoldtLSeriesMajorant_vertical
#print axioms AnalyticNumberTheory.Dirichlet.norm_intervalIntegral_negLogDerivLFunction_vertical_le
#print axioms AnalyticNumberTheory.Dirichlet.norm_intervalIntegral_negLogDerivLFunction_div_vertical_le
#print axioms AnalyticNumberTheory.Dirichlet.charOrthSumUnit
#print axioms AnalyticNumberTheory.Dirichlet.charOrthMulKernel
#print axioms AnalyticNumberTheory.Dirichlet.charOrthMulKernel_prime
#print axioms AnalyticNumberTheory.Dirichlet.charOrthKernel_prime_two
#print axioms AnalyticNumberTheory.Dirichlet.mem_nonprincipalCharacters
#print axioms AnalyticNumberTheory.Dirichlet.sum_chars_eq_principal_add_nonprincipal
#print axioms AnalyticNumberTheory.Dirichlet.charOrthMulKernel_prime_nonprincipal
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharKernelCollapse_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedPrincipalKernel_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedNonprincipalKernelCollapse_prime
#print axioms AnalyticNumberTheory.Dirichlet.characterSumOn_principal_prime
#print axioms AnalyticNumberTheory.Dirichlet.characterSumOn_secondMoment_prime
#print axioms AnalyticNumberTheory.Dirichlet.characterSumOn_principal_secondMoment_prime
#print axioms AnalyticNumberTheory.Dirichlet.characterSumOn_nonprincipal_secondMoment_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_secondMoment_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_principal_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_nonprincipal_secondMoment_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_nonprincipal_normSq_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_nonprincipal_normSq_le_prime
#print axioms AnalyticNumberTheory.Dirichlet.weightedCharacterSumOn_twistedSecondMoment_prime
#print axioms AnalyticNumberTheory.PrimeDistribution.mem_dyadicPrimeWindow
#print axioms AnalyticNumberTheory.PrimeDistribution.dyadicPrimeWindow_eq_primesLE_sdiff
#print axioms AnalyticNumberTheory.PrimeDistribution.card_dyadicPrimeWindow
#print axioms AnalyticNumberTheory.PrimeDistribution.dyadicPrimeWindow_nonempty
#print axioms AnalyticNumberTheory.PrimeDistribution.eventually_dyadicPrimeWindow_card_lower_bound
#print axioms AnalyticNumberTheory.Dirichlet.dyadicPrime_log_sub_log_nonneg
#print axioms AnalyticNumberTheory.Dirichlet.dyadicPrime_log_sub_log_le_log_two
#print axioms AnalyticNumberTheory.Dirichlet.dyadicPrimeLogCharacterSum_eq_log_mul_add_remainder
#print axioms AnalyticNumberTheory.Dirichlet.norm_dyadicPrimeLogRemainder_le
#print axioms AnalyticNumberTheory.Dirichlet.log_mul_norm_characterSumOn_dyadicPrimeWindow_le
#print axioms AnalyticNumberTheory.Dirichlet.norm_characterSumOn_dyadicPrimeWindow_le_div_log
#print axioms AnalyticNumberTheory.Dirichlet.dyadicVonMangoldtCharacterSum_eq_primeLog_add_nonprime
#print axioms AnalyticNumberTheory.Dirichlet.norm_dyadicVonMangoldtNonprimeRemainder_le
#print axioms AnalyticNumberTheory.Dirichlet.dyadicVonMangoldtNonprimeMass_le
#print axioms AnalyticNumberTheory.Dirichlet.norm_dyadicVonMangoldtNonprimeRemainder_le_sqrtLog
#print axioms AnalyticNumberTheory.Dirichlet.norm_dyadicPrimeLogCharacterSum_le_vonMangoldt_add_sqrtLog
#print axioms AnalyticNumberTheory.Dirichlet.norm_characterSumOn_dyadicPrimeWindow_le_vonMangoldt
#print axioms AnalyticNumberTheory.Dirichlet.dyadicVonMangoldtCharacterSum_eq_partial_sub_partial
#print axioms AnalyticNumberTheory.Dirichlet.norm_dyadicVonMangoldtCharacterSum_le_partial_add_partial
