import AnalyticNumberTheory.Dirichlet.VonMangoldtLSeries

#print axioms AnalyticNumberTheory.Dirichlet.twistedVonMangoldtLSeries_eq_negLogDerivLFunction
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.analyticAt_negLogDerivLFunction
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.analyticOnNhd_negLogDerivLFunction_halfPlane
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.exists_norm_negLogDerivLFunction_bound_on_compact
#print axioms AnalyticNumberTheory.Dirichlet.GRHAt.exists_norm_negLogDerivLFunction_bound_on_verticalSegment
#print axioms AnalyticNumberTheory.Dirichlet.norm_negLogDerivLFunction_le_vonMangoldtLSeriesMajorant
#print axioms AnalyticNumberTheory.Dirichlet.norm_negLogDerivLFunction_le_vonMangoldtLSeriesMajorant_vertical
#print axioms AnalyticNumberTheory.Dirichlet.norm_intervalIntegral_negLogDerivLFunction_vertical_le
#print axioms AnalyticNumberTheory.Dirichlet.norm_intervalIntegral_negLogDerivLFunction_div_vertical_le
