import AnalyticNumberTheory

/-!
# Kernel trust audit

CI checks every declaration listed below against an exact axiom whitelist:
`propext`, `Classical.choice`, and `Quot.sound`. In particular, `sorryAx` and
all other non-whitelisted axioms are rejected.
-/

#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevPsi_medium_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_medium_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_endpoint_error
#print axioms AnalyticNumberTheory.PrimeDistribution.primeCounting_asymptotic_real
#print axioms AnalyticNumberTheory.PrimeDistribution.NatPrimeCountingPNT
#print axioms AnalyticNumberTheory.PrimeDistribution.natPrimeCountingPNT
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct
#print axioms AnalyticNumberTheory.Mertens.abs_log_primeFactor_add_le
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalSum_eq_theta_abel
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalSum_eq_theta_div_mul_log_add_integral
#print axioms AnalyticNumberTheory.Mertens.theta_abel_main_term
#print axioms AnalyticNumberTheory.Mertens.norm_integral_Ioi_le_div_log
#print axioms AnalyticNumberTheory.Mertens.locallyIntegrableOn_theta
#print axioms AnalyticNumberTheory.Mertens.locallyIntegrableOn_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_isBigO
#print axioms AnalyticNumberTheory.Mertens.integrableOn_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_interval_sub_total_eq_neg_tail
#print axioms AnalyticNumberTheory.Mertens.intervalIntegrable_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.theta_weighted_integral_decomposition
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_tail_eventually
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_error_decomposition
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_eventually
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_nat
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_isBigO
#print axioms AnalyticNumberTheory.Mertens.neg_log_primeProduct_eq_reciprocal_add_correction
#print axioms AnalyticNumberTheory.Mertens.summable_logarithmicCorrectionTerm
#print axioms AnalyticNumberTheory.Mertens.tendsto_logarithmicCorrection
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrectionLimit_sub_eq_tail
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_norm_le
#print axioms AnalyticNumberTheory.Mertens.shifted_reciprocal_square_tail_le
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_norm_le_div
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_isBigO
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct_error_eq
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct_mertens_isBigO
#print axioms AnalyticNumberTheory.Mertens.zeta_log_vonMangoldt_isBigO
#print axioms AnalyticNumberTheory.Mertens.zeta_euler_log_eq_LSeries
#print axioms AnalyticNumberTheory.Mertens.primeEulerLog_tsum_decomposition
