import AnalyticNumberTheory

/-!
# Kernel trust audit

CI checks every declaration listed below against an exact axiom whitelist:
`propext`, `Classical.choice`, and `Quot.sound`. In particular, `sorryAx` and
all other non-whitelisted axioms are rejected.
-/

#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevPsi_medium_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_medium_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_error
#print axioms AnalyticNumberTheory.PrimeDistribution.chebyshevTheta_endpoint_error
#print axioms AnalyticNumberTheory.PrimeDistribution.primeCounting_asymptotic_real
#print axioms AnalyticNumberTheory.PrimeDistribution.NatPrimeCountingPNT
#print axioms AnalyticNumberTheory.PrimeDistribution.natPrimeCountingPNT
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct
#print axioms AnalyticNumberTheory.Mertens.abs_log_primeFactor_add_le
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalSum_eq_theta_abel
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalSum_eq_theta_div_mul_log_add_integral
#print axioms AnalyticNumberTheory.Mertens.theta_abel_main_term
#print axioms AnalyticNumberTheory.Mertens.norm_integral_Ioi_le_div_log
#print axioms AnalyticNumberTheory.Mertens.locallyIntegrableOn_theta
#print axioms AnalyticNumberTheory.Mertens.locallyIntegrableOn_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_isBigO
#print axioms AnalyticNumberTheory.Mertens.integrableOn_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_interval_sub_total_eq_neg_tail
#print axioms AnalyticNumberTheory.Mertens.intervalIntegrable_thetaErrorKernel
#print axioms AnalyticNumberTheory.Mertens.theta_weighted_integral_decomposition
#print axioms AnalyticNumberTheory.Mertens.thetaErrorKernel_tail_eventually
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_error_decomposition
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_eventually
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_nat
#print axioms AnalyticNumberTheory.Mertens.mertensSecond_isBigO
#print axioms AnalyticNumberTheory.Mertens.neg_log_primeProduct_eq_reciprocal_add_correction
#print axioms AnalyticNumberTheory.Mertens.summable_logarithmicCorrectionTerm
#print axioms AnalyticNumberTheory.Mertens.tendsto_logarithmicCorrection
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrectionLimit_sub_eq_tail
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_norm_le
#print axioms AnalyticNumberTheory.Mertens.shifted_reciprocal_square_tail_le
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_norm_le_div
#print axioms AnalyticNumberTheory.Mertens.logarithmicCorrection_tail_isBigO
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct_error_eq
#print axioms AnalyticNumberTheory.Mertens.log_primeProduct_mertens_isBigO
#print axioms AnalyticNumberTheory.Mertens.exp_log_primeProduct_error_isBigO
#print axioms AnalyticNumberTheory.Mertens.primeProduct_error_eq_canonical_factor
#print axioms AnalyticNumberTheory.Mertens.primeProduct_canonical_mertens_isBigO
#print axioms AnalyticNumberTheory.Mertens.primeProduct_mertens_isBigO_of_constant_eq
#print axioms AnalyticNumberTheory.Mertens.zeta_log_vonMangoldt_isBigO
#print axioms AnalyticNumberTheory.Mertens.zeta_euler_log_eq_LSeries
#print axioms AnalyticNumberTheory.Mertens.primeEulerLog_tsum_decomposition
#print axioms AnalyticNumberTheory.Mertens.summable_zeta_primeEulerLog
#print axioms AnalyticNumberTheory.Mertens.summable_zeta_primeDirichlet
#print axioms AnalyticNumberTheory.Mertens.summable_zeta_primeEulerCorrection
#print axioms AnalyticNumberTheory.Mertens.zeta_primeEulerLog_decomposition
#print axioms AnalyticNumberTheory.Mertens.real_primeEulerLog_eq_log_riemannZeta
#print axioms AnalyticNumberTheory.Mertens.norm_primeEulerCorrection_le
#print axioms AnalyticNumberTheory.Mertens.tendsto_primeEulerCorrection
#print axioms AnalyticNumberTheory.Mertens.tendsto_tsum_primeEulerCorrection
#print axioms AnalyticNumberTheory.Mertens.tsum_primeEulerCorrection_one
#print axioms AnalyticNumberTheory.Mertens.tendsto_tsum_primeEulerCorrection_limit
#print axioms AnalyticNumberTheory.Mertens.real_primeEulerLog_decomposition
#print axioms AnalyticNumberTheory.Mertens.complex_integral_log_mul_exp_eq_neg_eulerMascheroni
#print axioms AnalyticNumberTheory.Mertens.complex_integral_log_exp_eq_neg_eulerMascheroni
#print axioms AnalyticNumberTheory.Mertens.complex_scaled_integral_log_exp_eq_neg_eulerMascheroni
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalLSeries_eq_primeDirichletSum
#print axioms AnalyticNumberTheory.Mertens.sum_Icc_primeReciprocalCoeff
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalSum_isBigO_rpow
#print axioms AnalyticNumberTheory.Mertens.primeReciprocalLSeries_eq_mul_integral
#print axioms AnalyticNumberTheory.Mertens.primeDirichletSum_eq_mul_integral
#print axioms AnalyticNumberTheory.Mertens.primeDirichletSum_eq_mul_integral_of_pos
#print axioms AnalyticNumberTheory.Mertens.realPrimeDirichletSum_eq_mul_integral_of_pos
#print axioms AnalyticNumberTheory.Mertens.primeAbel_integral_log_change
#print axioms AnalyticNumberTheory.Mertens.tendsto_mul_integral_exp_remainder_of_integrable_norm_div
#print axioms AnalyticNumberTheory.Mertens.integrableOn_norm_div_of_compact_of_inv_tail
#print axioms AnalyticNumberTheory.Mertens.tendsto_mul_integral_exp_remainder_of_inv_tail
#print axioms AnalyticNumberTheory.Mertens.mertensConstant_eq_eulerMascheroni_of_primeFinitePart
