import AnalyticNumberTheory

-- Focused trust audit for the main→dev reconciliation slices.
-- These declarations come from exact main blobs staged by integration PRs.
#print axioms AnalyticNumberTheory.Sieve.panChebyshevMainStepLHS_abs_le_corrected
#print axioms AnalyticNumberTheory.Sieve.not_PanChebyshevMainStep
#print axioms AnalyticNumberTheory.LargeSieve.bombieriDavenport_vaughanThird
#print axioms AnalyticNumberTheory.LargeSieve.csSqrtSum_le_card_mul_sum
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_totientWeightSum_polylog
#print axioms AnalyticNumberTheory.LargeSieve.dirichletChar_eq_primitiveCharacter_of_coprime
#print axioms AnalyticNumberTheory.LargeSieve.dirichletChar_norm_le_one
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_char_induced_by_primitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIV1CharSum_eq_coprimePart
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_nonCoprimeDensity_nonneg
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIV1CharSum_norm_le_primitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_nonCoprimeDensity_le_primePartition
#print axioms AnalyticNumberTheory.Sieve.sum_powerset_two_pow_eq_three_pow
#print axioms AnalyticNumberTheory.Sieve.divisors_squarefree_filter_eq_self
#print axioms AnalyticNumberTheory.Sieve.sum_squarefree_divisors_eq_sum_powerset
#print axioms AnalyticNumberTheory.Sieve.three_pow_omega_eq_sum_two_pow
#print axioms AnalyticNumberTheory.Sieve.totient_div_self_le_one
#print axioms AnalyticNumberTheory.Sieve.panTypeIWeight3_le_sqfree_three_pow
#print axioms AnalyticNumberTheory.Sieve.panTypeIWeight3_le_Q_mul_sumTwoPowWeighted
#print axioms AnalyticNumberTheory.Sieve.panTypeIWeight3_le_polylog
#print axioms AnalyticNumberTheory.Sieve.totient_div_q_mul_q_div_totient_eq_one
#print axioms AnalyticNumberTheory.Sieve.q_div_totient_mul_totient_div_q_eq_one
#print axioms AnalyticNumberTheory.Sieve.mul_totient_div_q_mul_q_div_totient
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_liftPrimitive_isPrimitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_primitiveFiberSqSum_le
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIV1CharSum_sq_le_primitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_sqSum_primitiveDecomposition
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIPrimitiveSqSum_nonneg
#print axioms AnalyticNumberTheory.LargeSieve.panTypeI_charCard_eq_totient
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIIPrimitiveSqSum_nonneg
#print axioms AnalyticNumberTheory.LargeSieve.panTypeII_nonCoprimeDensity_nonneg
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIIV3CharSum_norm_le_primitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeIIV3CharSum_sq_le_primitive
#print axioms AnalyticNumberTheory.LargeSieve.panTypeII_primitiveFiberSqSum_le
#print axioms AnalyticNumberTheory.LargeSieve.panTypeII_sqSum_primitiveDecomposition
#print axioms AnalyticNumberTheory.LargeSieve.sum_multiples_eq_sum_range
#print axioms AnalyticNumberTheory.LargeSieve.log_mul_plus_one_le
#print axioms AnalyticNumberTheory.LargeSieve.prime_mul_divisors_card_le
